### ISSUE TITLE
Trouble importing Tqdm in Swift 5.9

### ISSUE THREAD

**Issue by AlienKevin** [ebraraktas/swift-tqdm#2]
Hi, thanks for porting tqdm over to Swift! For some reason though, I have trouble using your library in the Swift 5.9. When I do `swift build`, the compiler keeps complaining about:
```
product 'Tqdm' required by package 'test-swift-tqdm' target 'test-swift-tqdm' not found.
```

I made a minimal repro by creating a blank Swift executable using `swift package init --type executable`: https://github.com/AlienKevin/test-swift-tqdm

**Comment by ebraraktas** [comment]
I don't know what changed in SPM, but I found two solutions for the error:

1) Specify target dependency product:
```swift
// ...
targets: [
   // Targets are the basic building blocks of a package, defining a module or a test suite.
   // Targets can depend on other targets in this package and products from dependencies.
   .executableTarget(
     name: "test-swift-tqdm", dependencies: [.product(name: "Tqdm", package: "swift-tqdm")])
 ]
```
2) Specify package name in the `dependencies`. Note that, this pattern is deprecated and I don't recommend this:
```swift
.package(name: "Tqdm", url: "https://github.com/ebraraktas/swift-tqdm.git", from: "0.1.2")
```

Anyway, it may be better to rename rename the repository and package, but for now I will keep it this way and update related part in the README.
